#!/usr/bin/env python3
# Finalize offsets_db.json + generate the C header for the app and the
# markdown report.
import json, os, sys, time

BASE = '/home/z/my-project'
DB   = os.path.join(BASE, 'download/offsets_db.json')
HDR  = os.path.join(BASE, 'Whitelist/Whitelist/Exploit/KernelExploit/kernel_build_symbols.h')
REP  = os.path.join(BASE, 'download/offsets_report.md')

# hw.machine -> kernelcache suffix map (curated from Apple IPSW inspection)
DEVICE_SOC = [
    # A11 (iPhone 8 / 8 Plus / X)
    ("iPhone10,1", "iphone10"), ("iPhone10,2", "iphone10"),
    ("iPhone10,4", "iphone10"), ("iPhone10,5", "iphone10"),
    ("iPhone10,3", "iphone10"), ("iPhone10,6", "iphone10"),
    # A13 (iPhone 11 family, SE2) - kernelcache suffix iphone12b
    ("iPhone12,1", "iphone12b"), ("iPhone12,3", "iphone12b"),
    ("iPhone12,5", "iphone12b"), ("iPhone12,8", "iphone12b"),
    # A12 (iPhone XR/XS family) - suffix iphone12 (not covered by DB yet)
    ("iPhone11,8", "iphone12"), ("iPhone11,2", "iphone12"),
    ("iPhone11,4", "iphone12"), ("iPhone11,6", "iphone12"),
    # A14 (iPhone 12 family)
    ("iPhone13,1", "iphone13"), ("iPhone13,2", "iphone13"),
    ("iPhone13,3", "iphone13"), ("iPhone13,4", "iphone13"),
    # A15 (iPhone 13 family / SE3)
    ("iPhone14,4", "iphone14"), ("iPhone14,5", "iphone14"),
    ("iPhone14,2", "iphone14"), ("iPhone14,3", "iphone14"),
    ("iPhone14,6", "iphone14"),
    # A16 (iPhone 14 Pro family)
    ("iPhone15,2", "iphone15"), ("iPhone15,3", "iphone15"),
    # A15 (iPhone 14/14 Plus)
    ("iPhone14,7", "iphone15"), ("iPhone14,8", "iphone15"),
    # A16 (iPhone 15/15 Plus)
    ("iPhone15,4", "iphone15"), ("iPhone15,5", "iphone15"),
    # A17 Pro (iPhone 15 Pro family - no DB entries yet, harmless mapping)
    ("iPhone16,1", "iphone16"), ("iPhone16,2", "iphone16"),
    # A18 / A18 Pro (iPhone 16 family - shared kernelcache.release.iphone17)
    ("iPhone17,1", "iphone17"), ("iPhone17,2", "iphone17"),
    ("iPhone17,3", "iphone17"), ("iPhone17,4", "iphone17"),
]

def main():
    db = json.load(open(DB))
    entries = db['entries']
    # de-dup + sort
    seen = {}
    for e in entries:
        seen[(e['build'], e['soc'])] = e
    entries = sorted(seen.values(), key=lambda e: (e['ios_version'], e['build'], e['soc']))
    db['entries'] = entries
    db['schema'] = dict(
        offset_semantics=("allproc_offset = allproc_va - kernel_image_base, where "
                          "kernel_image_base is the __TEXT vmaddr of the kernel image "
                          "(com.apple.kernel fileset entry on iOS 17+, container on <=16). "
                          "Runtime: allproc = kernel_base + offset; the app's staticBase "
                          "cancels through slide."),
        lookup_key=("kern.osversion (build) + kernelcache suffix; devices sharing a "
                    "kernelcache share the offset"),
        method="XPF (opa334) shutdownwait xref port, cross-checked with multi-site agreement",
        generated_at=time.strftime('%Y-%m-%d %H:%M'))
    json.dump(db, open(DB, 'w'), indent=2)

    # ── C header ──
    lines = []
    a = lines.append
    a("// kernel_build_symbols.h - AUTO-GENERATED, DO NOT EDIT")
    a("// Generated by tools/offsets/build_offsets_db.py from offsets_db.json.")
    a("// Source: official Apple IPSW kernelcaches; allproc located with the")
    a("// XPF (opa334) shutdownwait method and multi-site agreement; each offset")
    a("// is live-validated by the app before use (proc0/launchd chain check).")
    a("//")
    a("// Offset semantics: allproc_offset is relative to the kernel image base")
    a("// (the image whose Mach-O header ClearSword finds at runtime), so")
    a("//     allproc = kernel_base + allproc_offset")
    a("// regardless of the staticBase constant used during slide computation.")
    a("#ifndef WL_BUILD_SYMBOLS_H")
    a("#define WL_BUILD_SYMBOLS_H")
    a("")
    a("#include <stdint.h>")
    a("#include <stddef.h>")
    a("")
    a("struct wl_build_symbol {")
    a("    const char* build;          // kern.osversion (e.g. \"20H392\")")
    a("    const char* soc;            // kernelcache suffix (e.g. \"iphone13\")")
    a("    uint64_t    allproc_offset; // from the kernel image base")
    a("    const char* ios_version;    // informational")
    a("};")
    a("")
    a("struct wl_device_soc {")
    a("    const char* device;         // hw.machine (e.g. \"iPhone13,2\")")
    a("    const char* soc;            // kernelcache suffix")
    a("};")
    a("")
    a("// One entry per (build, kernelcache). Multiple SoCs per build are listed")
    a("// separately - the offset differs per kernelcache even for one build.")
    a("static const struct wl_build_symbol s_build_symbols[] = {")
    for e in entries:
        a(f'    {{ "{e["build"]}", "{e["soc"]}", 0x{e["allproc_offset"]:x}ULL, '
          f'"{e["ios_version"]}" }},  // {e["device"]} ({e["kernelcache"]})')
    a("};")
    a("")
    a("// device identifier -> kernelcache suffix")
    a("static const struct wl_device_soc s_device_soc[] = {")
    for dev, soc in DEVICE_SOC:
        a(f'    {{ "{dev}", "{soc}" }},')
    a("};")
    a("")
    a("#endif /* WL_BUILD_SYMBOLS_H */")
    os.makedirs(os.path.dirname(HDR), exist_ok=True)
    open(HDR, 'w').write('\n'.join(lines) + '\n')

    # ── report ──
    r = []
    ra = r.append
    ra('# Whitelist allproc offsets DB - multi-iOS pipeline report')
    ra('')
    ra(f'Generated: {time.strftime("%Y-%m-%d %H:%M")} | pipeline: scripts/build_offsets_db.py')
    ra('')
    ra('## Verified entries (offline XPF + multi-site agreement)')
    ra('')
    ra('| build | iOS | device | kernelcache | staticBase (file) | allproc VA | offset |')
    ra('|---|---|---|---|---|---|---|')
    for e in entries:
        ra(f'| {e["build"]} | {e["ios_version"]} | {e["device"]} | {e["kernelcache"]} | '
           f'`{hex(e["static_base"])}` | `{hex(e["allproc_va"])}` | `0x{e["allproc_offset"]:x}` |')
    ra('')
    ra('Same-build/different-SoC pairs (20G81, 21H16) demonstrate that the lookup')
    ra('key MUST be (build, kernelcache-suffix) - offsets differ per kernelcache.')
    ra('')
    ra('## iOS 18.x / 26.x status - RESOLVED')
    ra('')
    ra('The xnu 11215 refactor (iOS 18.0) moved the allproc deref out of the')
    ra('panic("shutdownwait") site into proc_iterate, reachable through a `b`')
    ra('tail-call after the string is materialised into a callee-saved register')
    ra('(x24 on the inspected builds). Two bugs in the previous offline port')
    ra('made 18+/26 fail while the same code worked on 15-17:')
    ra('')
    ra('1. mov x3, Xm constant was 0xAA2003E0 (bit 21/N wrongly set) instead of')
    ra('   0xAA0003E0 - the mov could never be recognised.')
    ra('2. Only ADRP_ADD xrefs were scanned; XPF\'s REFERENCE mask also covers')
    ra('   ADR / ADRP_LDR / ADRP_STR (the 26.x site uses ADR).')
    ra('')
    ra('With both fixed (current pipeline), 18.x and 26.x resolve like any other')
    ra('version. Entries above include 22G100 (18.6.2) for iphone17/iphone15/')
    ra('iphone14, 22C161 (18.2.1) iphone14, 23A355 (26.0.1) iphone17 and 23G83')
    ra('(26.6.1) iphone15. Each offset is still live-validated by the app')
    ra('(proc0/launchd chain) before any kernel write.')
    ra('')
    ra('unsandbox on iOS 15.2+/17+/18/26 uses the proc_ro path (ucred at')
    ra('proc_ro+0x20/0x28) exactly like Dopamine libjailbreak - no version gate.')
    ra('')
    ra('## Runtime contract (app side)')
    ra('')
    ra('1. kern.osversion + hw.machine -> kernelcache suffix -> s_build_symbols entry.')
    ra('2. allproc = kernel_base + offset (staticBase cancels via slide).')
    ra('3. Live validation BEFORE first use (read-only): allproc.lh_first -> proc0,')
    ra('   proc0.le_prev == &allproc, proc0.p_pid == 0, next.p_pid == 1 (launchd).')
    ra('   Any mismatch -> return 0, no kernel write ever happens.')
    open(REP, 'w').write('\n'.join(r) + '\n')
    print(f'entries: {len(entries)}')
    for e in entries:
        print(f"  {e['build']}/{e['soc']}: 0x{e['allproc_offset']:x} (iOS {e['ios_version']})")
    print('header ->', HDR)
    print('report ->', REP)

if __name__ == '__main__':
    main()
