name: Build IPA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
        xcodebuild -version

    - name: Clean
      run: make clean

    - name: Resolve Packages & Build
      run: |
        xcodebuild -project Whitelist.xcodeproj \
          -target Whitelist \
          -configuration Release \
          -sdk iphoneos \
          -resolvePackageDependencies \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS=NO \
          ENABLE_PREVIEWS=NO \
          DEVELOPMENT_ASSET_PATHS="" \
          build

    - name: Package IPA
      run: |
        make entitlements
        make package

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: Whitelist IPA
        path: Whitelist.ipa
